### ISSUE TITLE
Import data from xml files

### ISSUE THREAD

**Issue by igorlaltuf** [igorlaltuf/dail#3]
The csv format files provided by CGU are not well formatted. Apparently the problem does not occur with files in xml format.

**Comment by reichaves** [comment]
Hello Igor. I encountered this same problem, downloading the CSV files in Python. I downloaded in XML and it worked - https://github.com/abraji/LAI/blob/main/busca_lai_cgu.py

**Comment by igorlaltuf** [comment]
Apparently, it was not possible to import some of the files in XML format by R using Windows. 

I contacted CGU, who already made the corrections in the lines of the CSV files that were badly formatted. 

However, the CSV files with the appeals are empty. I have already contacted them and am waiting for a response. 

Note that instead of using: requests_all( ) you should use requests(search = 'all') since version 1.3. 

CRAN version will be available soon.
